// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BrewWholesaleDbContext))]
    [Migration("20251014163957_SeedData_Initial")]
    partial class SeedData_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Beer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AlcoholDegree")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BreweryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceHtva")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BreweryId");

                    b.ToTable("Beers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            AlcoholDegree = 6.6m,
                            BreweryId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Leffe Blonde",
                            PriceHtva = 2.20m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            AlcoholDegree = 9.0m,
                            BreweryId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Chimay Bleue",
                            PriceHtva = 2.80m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            AlcoholDegree = 6.2m,
                            BreweryId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Orval",
                            PriceHtva = 2.60m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            AlcoholDegree = 9.5m,
                            BreweryId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Westmalle Triple",
                            PriceHtva = 3.10m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            AlcoholDegree = 8.5m,
                            BreweryId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Duvel",
                            PriceHtva = 2.90m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            AlcoholDegree = 6.0m,
                            BreweryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Zinnebir",
                            PriceHtva = 2.40m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            AlcoholDegree = 8.5m,
                            BreweryId = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Delirium Tremens",
                            PriceHtva = 3.20m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            AlcoholDegree = 5.0m,
                            BreweryId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Cantillon Gueuze",
                            PriceHtva = 4.50m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            AlcoholDegree = 7.0m,
                            BreweryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Speculoos Stout",
                            PriceHtva = 2.70m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            AlcoholDegree = 5.8m,
                            BreweryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Frites IPA",
                            PriceHtva = 2.30m
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            AlcoholDegree = 6.2m,
                            BreweryId = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "La Blonde des Marolles",
                            PriceHtva = 2.10m
                        });
                });

            modelBuilder.Entity("Core.Entities.Brewery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Breweries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Abbaye de Leffe"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Abbaye de Scourmont (Chimay)"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Abbaye d'Orval"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Name = "Abbaye de Westmalle"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Name = "Duvel Moortgat"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Name = "Brasserie de la Senne"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Name = "Brasserie Huyghe (Delirium)"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Name = "Brasserie Cantillon"
                        });
                });

            modelBuilder.Entity("Core.Entities.WholesaleBeer", b =>
                {
                    b.Property<Guid>("WholesalerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BeerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("WholesalerId", "BeerId");

                    b.HasIndex("BeerId");

                    b.ToTable("WholesaleBeers");

                    b.HasData(
                        new
                        {
                            WholesalerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SalePrice = 2.25m,
                            Stock = 50
                        },
                        new
                        {
                            WholesalerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SalePrice = 2.30m,
                            Stock = 120
                        },
                        new
                        {
                            WholesalerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000001"),
                            SalePrice = 2.20m,
                            Stock = 0
                        },
                        new
                        {
                            WholesalerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SalePrice = 2.95m,
                            Stock = 35
                        },
                        new
                        {
                            WholesalerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000002"),
                            SalePrice = 3.05m,
                            Stock = 12
                        },
                        new
                        {
                            WholesalerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SalePrice = 2.80m,
                            Stock = 8
                        },
                        new
                        {
                            WholesalerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000003"),
                            SalePrice = 2.85m,
                            Stock = 22
                        },
                        new
                        {
                            WholesalerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SalePrice = 3.30m,
                            Stock = 18
                        },
                        new
                        {
                            WholesalerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000004"),
                            SalePrice = 3.25m,
                            Stock = 2
                        },
                        new
                        {
                            WholesalerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            SalePrice = 3.05m,
                            Stock = 200
                        },
                        new
                        {
                            WholesalerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000005"),
                            SalePrice = 3.10m,
                            Stock = 15
                        },
                        new
                        {
                            WholesalerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000006"),
                            SalePrice = 2.55m,
                            Stock = 40
                        },
                        new
                        {
                            WholesalerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            SalePrice = 3.40m,
                            Stock = 25
                        },
                        new
                        {
                            WholesalerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000007"),
                            SalePrice = 3.50m,
                            Stock = 10
                        },
                        new
                        {
                            WholesalerId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000008"),
                            SalePrice = 4.90m,
                            Stock = 6
                        },
                        new
                        {
                            WholesalerId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000009"),
                            SalePrice = 2.90m,
                            Stock = 11
                        },
                        new
                        {
                            WholesalerId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000010"),
                            SalePrice = 2.45m,
                            Stock = 9
                        },
                        new
                        {
                            WholesalerId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BeerId = new Guid("00000000-0000-0000-0000-000000000010"),
                            SalePrice = 2.55m,
                            Stock = 21
                        });
                });

            modelBuilder.Entity("Core.Entities.Wholesaler", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Wholesalers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Name = "HygieDrinks"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Name = "BelgoDistrib"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Name = "BruxDrinks"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            Name = "WallonBoissons"
                        });
                });

            modelBuilder.Entity("Core.Entities.Beer", b =>
                {
                    b.HasOne("Core.Entities.Brewery", "Brewery")
                        .WithMany("Beers")
                        .HasForeignKey("BreweryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brewery");
                });

            modelBuilder.Entity("Core.Entities.WholesaleBeer", b =>
                {
                    b.HasOne("Core.Entities.Beer", "Beer")
                        .WithMany("WholesaleBeers")
                        .HasForeignKey("BeerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Wholesaler", "Wholesaler")
                        .WithMany("WholesaleBeers")
                        .HasForeignKey("WholesalerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beer");

                    b.Navigation("Wholesaler");
                });

            modelBuilder.Entity("Core.Entities.Beer", b =>
                {
                    b.Navigation("WholesaleBeers");
                });

            modelBuilder.Entity("Core.Entities.Brewery", b =>
                {
                    b.Navigation("Beers");
                });

            modelBuilder.Entity("Core.Entities.Wholesaler", b =>
                {
                    b.Navigation("WholesaleBeers");
                });
#pragma warning restore 612, 618
        }
    }
}
